# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0002_auto_20171129_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='banner',
            field=models.CharField(default='', max_length=20),
        ),
    ]
