# Generated by Django 2.0 on 2017-12-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0003_serie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.CharField(default='', max_length=64),
        ),
    ]
