# Generated by Django 2.0 on 2017-12-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0005_auto_20171203_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
