# Generated by Django 2.0 on 2017-12-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0006_auto_20171203_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='note',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
