# Generated by Django 2.0 on 2017-12-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0007_film_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(default=''),
        ),
    ]
