# Generated by Django 2.0 on 2017-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0009_auto_20171205_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='titre',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
