# Generated by Django 2.0 on 2017-12-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0010_auto_20171205_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
