# Generated by Django 2.0 on 2017-12-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacksheep', '0011_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='date_sortie',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
